version: '3.8'

services:
  backend:
    build:
      context: ./worldBank-bff
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./worldBank-fed
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge